test:
  app_suffix: deals
  org: TW-org
  space: test
  is_service: true
  dependency_service_app_suffixes:
    - pricing
production:
  app_suffix: deals
  org: TW-org
  space: production
  is_service: true
  dependency_service_app_suffixes:
    - pricing
