defaults: &defaults
  app_suffix: deals
  org: TW-org
  is_service: true
  dependency_service_app_suffixes:
    - pricing
test:
  <<: *defaults
  space: test
production:
  <<: *defaults
  space: production
