db:
  image: postgres

pricing:
  build: pretend_pricing_service
  ports: [80]
  dns: &dns
    - 172.17.0.1 # docker host bridge IP; connects to consul-server running on host net
    - 8.8.8.8

deals:
  build: pretend_deals_service
  ports: [80]
  dns: *dns

catalog:
  build: pretend_catalog_service
  dns: *dns

web:
  build: pretend_web_app
  ports: ["8081:80"]
  dns: *dns

consul:
  build: consul-server
  net: host
  command: -bootstrap

registrator:
  image: gliderlabs/registrator:master
  command: "-internal -retry-interval 500 -retry-attempts 10 consul://localhost:8500"
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  net: host
  
