db:
  image: postgres

pricing:
  build: pretend_pricing_service
  ports: [80]
  links: [db]

deals:
  build: pretend_deals_service
  ports: [80]
  links: [pricing]

catalog:
  build: pretend_catalog_service
  ports: [80]

web:
  build: pretend_web_app
  ports:
    - "8081:80"
  links:
    - deals
    - catalog

logspout:
  image: organizeme/logspout-logstash:latest
  environment:
    LOGSPOUT: ignore
    ROUTE_URIS: logstash://logstash:5000
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links: 
    - logstash
  ports: [8000]

logstash:
  image: logstash:2.0.0
  ports: 
    - "5000/udp"
    - "5000/tcp"
  environment:
    LOGSPOUT: ignore
  volumes:
    - "${PWD}/elk:/config-dir"
  command:
    logstash -f /config-dir/logstash.conf
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:2.0.0
  command:
    - "elasticsearch"
    - "--network.host"
    - "_non_loopback_"

kibana:
  image: kibana:4.2.0
  ports: ["5601:5601"]
  links:
    - elasticsearch


consul:
  image: gliderlabs/consul-server:latest
  command: -bootstrap
  net: host

registrator:
  image: gliderlabs/registrator:latest
  command: consul://localhost:8500
  net: host
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  
