db:
  image: postgres

pricing:
  build: pretend_pricing_service
  ports: [80]
  links: [db]

deals:
  build: pretend_deals_service
  ports: [80]
  links: [pricing]

catalog:
  build: pretend_catalog_service
  ports: [80]

web:
  build: pretend_web_app
  ports:
    - "8081:80"
  links:
    - deals
    - catalog


consul:
  image: gliderlabs/consul-server:latest
  command: -bootstrap
  net: host

registrator:
  image: gliderlabs/registrator:latest
  command: consul://localhost:8500
  net: host
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  
