# A sample Gemfile
source "https://rubygems.org"

gem "rake"

gem "sinatra"
gem "sinatra-contrib"

gem "haml"

gem 'puma'

gem 'microscope_tracer', '~> 0.2.0'

gem "faraday"
gem "faraday_middleware"
gem 'lazy_doc'

gem 'cloudfoundry-deploy', :git => 'https://github.com/ThoughtWorks-AELab/cloudfoundry-deploy.git'

group :development, :test do
  gem 'foreman'
  gem 'dotenv'
  gem 'rspec', '~> 3.3.0'
  gem 'ci_reporter_rspec'
  gem 'pry'
end

group :development do
  gem 'pry-nav'
end

